### ISSUE TITLE
ImportError: No module named pypykatz_server.server

### ISSUE THREAD

**Issue by mobdk** [skelsec/pypykatz_server#4]
Have installed pypykatz with git clone and the same for pypykatz_server, try to start server with
server.py socket -l 0.0.0.0 -p 80 get this error:

Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from pypykatz_server.server import *
ImportError: No module named pypykatz_server.server

**Comment by skelsec** [comment]
pull the server and try it again pls. I managed to remove the __init__.py file from the directory
let me know if this solved the issue.

**Comment by mobdk** [comment]
now I get this error:

ImportError: No module named pypykatz.commons.common

**Comment by mobdk** [comment]
sorry this is all:

Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from pypykatz_server.server import *
  File "/home/pi/pypykatz_server/pypykatz_server/server/__init__.py", line 1, in <module>
    from pypykatz_server.server.pypysocketserver import ThreadedPYPYSocketServer
  File "/home/pi/pypykatz_server/pypykatz_server/server/pypysocketserver.py", line 3, in <module>
    from pypykatz_server.reader.remotereader import *
  File "/home/pi/pypykatz_server/pypykatz_server/reader/remotereader.py", line 4, in <module>
    from pypykatz.commons.common import *
ImportError: No module named pypykatz.commons.common

**Comment by mobdk** [comment]
Hi, any news regarding this issue ? I tried running your code on windows, same problem.

**Comment by mobdk** [comment]
Hi, any news regarding this issue ?

**Comment by skelsec** [comment]
I have set up a vanilla Ubuntu desktop just to investigate this issue, as on all other platform I was successful in running the app. 
The bottom line is: even with a vanilla installation everything is working fine. I cannot reproduce this issue, and seeing that noone had commented on this for longer than a week, I believe the problem is on your end.

```
pip install pypykatz
git clone https://github.com/skelsec/pypykatz_server.git
python3 server.py socket
```
